image: gradle:latest

stages:
  - build
  - test

build:
  stage: build
  script:
    - gradle assemble

test:
  stage: test
  script:
    - gradle test

java:
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml