image: gradle:latest

stages:
  - test


test:
  stage: test
  script:
    - gradle test

java:
  stage: test
  script:
    - gradle test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml